# Generated by Django 2.2.24 on 2022-01-06 13:53

from django.db import migrations
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_untranslated_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='score_json',
            field=django_jsonfield_backport.models.JSONField(default=dict, verbose_name='Score'),
        ),
    ]
