# Generated by Django 2.2.24 on 2022-01-06 14:41

from django.db import migrations
from django.conf import settings
from django.utils.translation import activate
import re


def forwards_func(apps, schema_editor):
    Progress = apps.get_model("quiz", "Progress")
    Category = apps.get_model("quiz", "Category")

    activate("en")
    for progress in Progress.objects.all():
        for category in Category.objects.all():
            to_find = re.escape(category.category) + r",(\d+),(\d+),"
            match = re.search(to_find, progress.score, re.IGNORECASE)

            if match:
                progress.score_json[str(category.id)] = {
                    "score": int(match.group(1)),
                    "possible": int(match.group(2)),
                }
        progress.save()


def backwards_func(apps, schema_editor):
    Progress = apps.get_model("quiz", "Progress")
    Category = apps.get_model("quiz", "Category")

    for progress in Progress.objects.all():
        for category_id, values in progress.score_json.items():
            category = Category.objects.get(pk=category_id)
            name = category.category
            score = progress.score_json["score"]
            possible = progress.score_json["possible"]
            progress.score += f"{name},{score},{possible},"
        progress.save()


class Migration(migrations.Migration):

    dependencies = [("quiz", "0005_move_score_csv_to_json")]

    operations = [migrations.RunPython(forwards_func, backwards_func)]
