# Generated by Django 2.2.24 on 2022-01-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("quiz", "0006_remove_csv_score")]

    operations = [migrations.RemoveField(model_name="progress", name="score")]
