# Generated by Django 2.2.24 on 2022-01-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("quiz", "0007_remove_progress_score")]

    operations = [
        migrations.RenameField(
            model_name="progress", old_name="score_json", new_name="score"
        )
    ]
